### ISSUE TITLE
Obvi 291: When selecting the ford logo to leave the section I see the "About the Grants Database" message pop-up for a second before returning to the home screen automatically

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#12]
Reported by Peter

http://puu.sh/hGhRO/a8749427a1.png

FOR0072-708. This is an issue related to Angular. To hardcode resolution at launch.

**Comment by bobpullin** [comment]
FOR0072-708.  This is an issue related to Angular.  To hardcode resolution at launch.

**Comment by ttrevisan** [comment]
Appears resolved.
