### ISSUE TITLE
Obvi 363: Functionality bug. I open Originating Office drop down. I select and search for multiple offices. I reopen drop down, click “uncheck all” and then “Apply and Close.” The offices all remain checked.

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#16]
http://puu.sh/il6dj/5789349c2d.png
Terry: FOR0072-656 added to Sprint 15.  To be brought forward if possible.
Terry: Issue still active. I've attached a screenshot to help guide. Thanks
Terry: Extended to Sprint 18

**Comment by bobpullin** [comment]
Don't see check boxes checked but number of grants and amount holds

**Comment by ttrevisan** [comment]
I tested this in staging and live and it appeared resolved

**Comment by ttrevisan** [comment]
Fixed in OCT closing now
