### ISSUE TITLE
Obvi 369: "Uncheck all" bug. After selecting filters, then clicking on "uncheck all" and "apply" filters are not removed.

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#18]
Terry: Thomas, please can we discuss - I am unsure of the requirement.  Please can you add a screenshot and a link to the requirement.  Thanks

Terry: FOR0072-676 added to Sprint 15

Terry: FOR0072-711 - in progress.

http://puu.sh/iliax/986e098b88.png

**Comment by ttrevisan** [comment]
this functionality looks restored.
