### ISSUE TITLE
Obvi 385: Mobile: When navigating up and down a page, Hero images resizes on Android. Doesn't seem to happen on iPhone

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#20]
Reported by: Thomas

Terry: FOR0072-682 added to Sprint 15

Terry: Blocked pending discussion to confirm whether we should 'fix' the hero height on 'phone' devices

Terry: Proceed with suggestion

**Comment by ttrevisan** [comment]
completd
