### ISSUE TITLE
On Thematic Area landing pages close up space between Grant Makers and Blog subhead to match

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#35]
On Region landing pages it looks good:
https://www.dropbox.com/s/rx5hrrhlzfja8z4/space%20between%20grantmakers%20and%20blog.jpg?dl=0

On Thematic Area landing pages there is too much vertical space:
https://www.dropbox.com/s/e5dkejezw6z1wnk/space%20between%20grant%20makers%20and%20blog%20on%20TA%20pages.jpg?dl=0

**Comment by ttrevisan** [comment]
Completed
