### ISSUE TITLE
link from filtered chart not filtered in grants viz Purple section. 

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#39]
Filtered by Human Rights, revealed region level bar charts, selected bar chart for Beijing, got a page showing all grants to Beijing, not just Human Rights.

**Comment by terrybalfour** [comment]
Filter not working - clicking on a 'Human Rights' filtered list then clicking to Originating Office detail returns all grants for that office.  Not just those filtered.

**Comment by terrybalfour** [comment]
For launch - remove ability to click on filtered bar chart for an office.

Post launch - add filtering functionality (Issue + Originating Office)

**Comment by bobpullin** [comment]
Fixed
