### ISSUE TITLE
JustFilms not using the correct topic filters, appears to be pulling topics from blog. See comment

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#40]
If we can't fix this for launch we need to hide filter button

Arts, Culture and Media
Cities
Climate Change / Natural Resources
Criminal Justice Reform
Democratic and Accountable Government
Economic Justice
Education and Youth
Gender and Sexuality
Human Rights
Internet and Technology
Racial Justice

**Comment by ttrevisan** [comment]
this appears resolved.

**Comment by bobpullin** [comment]
On content.fordfoundation.org and on staging the filter is still hidden so I can't see if it's using the new filter topics

**Comment by bobpullin** [comment]
fixed
