### ISSUE TITLE
Grants viz green section: detail maps not place properly

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#43]
![green section grants viz detail maps not place properly](https://cloud.githubusercontent.com/assets/12086465/10653306/4f42e0ac-782c-11e5-82b3-bad191a7bcf4.jpg)

**Comment by grahamsw** [comment]
limited zoom options

**Comment by bobpullin** [comment]
Fixed by Graham

**Comment by ttrevisan** [comment]
irrelevant moving forward
