### ISSUE TITLE
Grants viz, green section, Initiative selection dropdown. Remove checkboxes at Issue level.

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#44]
Very important to China

![image001](https://cloud.githubusercontent.com/assets/12086465/10653932/5721ef2e-7832-11e5-9fa5-dff50dd87dce.jpg)

**Comment by terrybalfour** [comment]
Fixed pending Release

**Comment by bobpullin** [comment]
fixed
