### ISSUE TITLE
grants viz, orange section: selected Issue, selected Initiative bar chart, landing on list of grants for that initiative; map is misaligned

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#47]
![grantmaking by initiative - map not placed right](https://cloud.githubusercontent.com/assets/12086465/10654590/4c6416cc-783a-11e5-924d-b242808a7aed.jpg)

**Comment by grahamsw** [comment]
not a bug - width of map changes with page width
