### ISSUE TITLE
Grants viz, orange and purple sections: detail maps improperly placed

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#49]
![orange section detail map too wide](https://cloud.githubusercontent.com/assets/12086465/10714123/45435774-7ab3-11e5-9afb-df1ba4f40f61.jpg)

**Comment by grahamsw** [comment]
same carto javascript code used on green section detail map positions OK

**Comment by terrybalfour** [comment]
Javascript rendering bug on load - if refresh the map renders.  Possibly due to the size of the iFrame.  To timebox to two hours to see whether a size change resolves this.

Graham to arrange a call with CartoDB.

**Comment by bobpullin** [comment]
area for map on Originating Office grant detail view too wide, can we make it the same width as other detail views
![map is better width than originating office detail view](https://cloud.githubusercontent.com/assets/12086465/10871472/d476ac90-80b5-11e5-8c26-27bb3962d12c.jpg)

![map area to wide to avoid multiple worlds problem](https://cloud.githubusercontent.com/assets/12086465/10871455/73299c9a-80b5-11e5-8dc1-c171a4ab527e.jpg)

**Comment by ttrevisan** [comment]
Closing due to these section becoming irrelevant.
