### ISSUE TITLE
Region / History page, H1 "History" is too small, image should extend to top of page and logo and main nav should be white. Same goes for International Fellowships page

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#56]
![top nav bar should show photo](https://cloud.githubusercontent.com/assets/12086465/10711179/8e6f2c1a-7a41-11e5-8242-4eec45717911.jpg)

**Comment by ttrevisan** [comment]
Closing here -- it is documented in https://docs.google.com/spreadsheets/d/1R3DtuWXocS2BmJOtEEszOog-aGj0SQpHHofHJ2MYjbI/edit?ts=5643bf73#gid=0 on line 33
