### ISSUE TITLE
JustFilms partner page, image should appear behind top nav area --- also H1 too small

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#63]
![justfilms partner page nav should show photo behind it](https://cloud.githubusercontent.com/assets/12086465/10773105/e91ae1aa-7ccf-11e5-97cb-cbcc4a217f95.jpg)

http://fordfoundcontent.azurewebsites.net/work/our-grants/justfilms/justfilms-partners/

**Comment by ttrevisan** [comment]
I updated the priority spreadsheet to include this

**Comment by ttrevisan** [comment]
Closing here -- it is documented in https://docs.google.com/spreadsheets/d/1R3DtuWXocS2BmJOtEEszOog-aGj0SQpHHofHJ2MYjbI/edit?ts=5643bf73#gid=0 on line 33
