### ISSUE TITLE
Missing image on content.fordfoundation.org

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#66]
content.fordfoundation.org is missing a page imagery image on Latest card and blog post, while fordfoundcontent.azurewebsites.net shows the image successsfully

http://content.fordfoundation.org/ideas/equals-change-blog/posts/creating-lasting-progress-for-the-poorest-of-the-poor/

**Comment by grahamsw** [comment]
Image name had double extension (.jpg.jpg) which is throwing the firewall. Fixing the image name should fix that. I've reported the firewall issue but do not expect a fix.
