### ISSUE TITLE
On Latest feed, dates on blog post cards show the date the post was created instead of the publication date (editable field)

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#67]
- On Feed blog post cards we see date post was created
- On blog indexes "author", "date", "topic" we see date created
- On post itself we see publication date

All of these contexts should use publication date (because that we can set. This should also allow us to change where an item shows up in the feed by adjusting publication date).

**Comment by ttrevisan** [comment]
FFDDBUG-121

**Comment by bobpullin** [comment]
dates on both the index and the detail page are now the same date although they are each in a different format - date format on index is correct

**Comment by ttrevisan** [comment]
@ttrevisan checking in with durable on this work. Currently in tech review

**Comment by ttrevisan** [comment]
@bobpullin publication date change functionality IS active - however it seems the latest card version of that post still reflects the date created, not the publication date. I've slated this work to be reviewed and scheduled in Jira

**Comment by grahamsw** [comment]
resolved. (The test for whether the publication date was set was too stringent.)
