### ISSUE TITLE
region back button glitch resulting in two languages at once

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#78]
on brazil landing page choose portugese, click through to region history, hit back button. the TA landing page now shows one Line of Work in english and others in Portugese, also graphic link to history page shows both english and portugese versions. 
![region glitch - two languages at the same time](https://cloud.githubusercontent.com/assets/12086465/10893268/f13fdf66-8175-11e5-90fe-257870b7b72d.jpg)

![region glitch part 2 two languages at the same time](https://cloud.githubusercontent.com/assets/12086465/10893273/f61495ea-8175-11e5-8167-945dc7a2a727.jpg)

**Comment by ttrevisan** [comment]
I tested this and it's been fixed
