### ISSUE TITLE
Obvi 164: PRIORITY - Change email signup page to reflect new icons and 6 programs (instead of 8)

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#8]
http://fordfoundcontent.azurewebsites.net/email-updates/

Terry: FOR0072-497 reopened and added to Sprint 18 to add icons

**Comment by bobpullin** [comment]
FOR0072-497 reopened and added to Sprint 18 to add icons.

**Comment by ttrevisan** [comment]
This looks up to date now. @bobpullin can you review the page and confirm?

**Comment by bobpullin** [comment]
this thematic area focused version of the design was superseded by a topic focused version. see new design.

[FF Subscription Options 20150916 JL A.pdf](https://github.com/FordFoundation/Redesign2015/files/24939/FF.Subscription.Options.20150916.JL.A.pdf)

**Comment by bobpullin** [comment]
no longer relevant
