### ISSUE TITLE
Facebook image glitch

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#86]
![facebook image glitch](https://cloud.githubusercontent.com/assets/12086465/11305821/8e062efe-8f7c-11e5-8019-f6e4871ab203.jpg)

It seems to be pulling a small chunk of image from upper left corner of hero image instead of using the  dedicated social image created by cropper tool

Here's the hero image it seems to be pulling from:
http://www.fordfoundation.org/ideas/equals-change-blog/posts/answering-your-questions-about-fordforward/

**Comment by ttrevisan** [comment]
@bobpullin I'm looking into a solution here.

**Comment by ttrevisan** [comment]
FRP-111

**Comment by ttrevisan** [comment]
FFDDBUG 144

**Comment by ttrevisan** [comment]
This can be closed I believe, @bobpullin can you confirm?
