### ISSUE TITLE
dynamic blog link is incorrect on Michael Brennan bio

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#87]
On this page:  
http://www.fordfoundation.org/people/michael-brennan/mbrennan.net 
blog link appearing below twitter feed should go to external URL, instead goes here:
http://www.fordfoundation.org/people/michael-brennan/mbrennan.net

**Comment by ttrevisan** [comment]
@bobpullin I cannot reproduce this issue.
