### ISSUE TITLE
Date format site wide should be "1 October 2015" - Library currently has correct format on landing page but it's wrong on the publication detail page

### ISSUE THREAD

**Issue by bobpullin** [FordFoundation/Redesign2015#89]

**Comment by ttrevisan** [comment]
Hi Bob - can you provide a sample link?

**Comment by bobpullin** [comment]
See the date on the linked page, it reads  "January 15, 1936" when it should be as it is on the index  "15 January 1936" [Charter of Incorporation](http://www.fordfoundation.org/library/governance-documents/charterarticles-of-incorporation/)

**Comment by bobpullin** [comment]
Graham fixed this
